### PR TITLE
add full node path to merge errors in case it contains an array element

### PR DESCRIPTION
**Pull request by JamesClonk**
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

### CODE REVIEW

**Comment by JamesClonk** [comment]
Should make it somewhat easier to pinpoint a merge error in a template file, compared to having to manually figure out which exact node has the error.

```
2015/04/13 12:34:47 error generating manifest: unresolved nodes:
        (( merge ))     in templates/template.yml       jobs.[17].networks.[0].static_ips    (jobs.nats.networks.default.static_ips)
```

**Comment by fraenkel** [comment]
@JamesClonk Thanks for your pull request.
Rather than looking for a .[ in the context, it would make more sense if we just add a Path to the UnresolvedNode that was populated if we hit a []yaml.Node in findUnresolvedNodes and build it there.

**Comment by JamesClonk** [comment]
@fraenkel
Is it OK like this?

**Comment by fraenkel** [comment]
@JamesClonk Thanks. This looks much cleaner.

**Pull request closed without merging**
