### PR TITLE
[ci] build step & pipeline example for spiff into docker image

### PR DESCRIPTION
**Pull request by drnic**
`ci/pipeline.yml` is an example concourse pipeline to compile `spiff` for linux;
then bundle into a busybox image and push to Docker Hub.

job

https://registry.hub.docker.com/u/drnic/spiff/ is an example.

### CODE REVIEW

**Comment by drnic** [comment]
This is the pattern I've seen elsewhere - `Dockerfile` and `build.yml` in the root folder. But I think they could both go in `ci` to clean up the root folder.

**Comment by drnic** [comment]
Moved all files related to building docker image of spiff into `ci/` folder

**Comment by ematpl** [comment]
Hi, Dr Nic,

Thanks very much for the contribution. I have a few questions and concerns about the pipeline, though. First, could you explain more about the utility of having spiff on its own in a Docker image? We've found it more useful as a tool to add to a Docker image alongside other resources. For example, when we build the pipeline Docker image for diego-release, we [download spiff from one of its GitHub releases and unzip it onto the PATH in the image](https://github.com/cloudfoundry-incubator/diego-release/blob/develop/pipeline-image/Dockerfile#L3-L6). It would seem more useful to publish compiled spiff artifacts as a GitHub release like we do today manually, but for that to be fully automated we would want a more sophisticated pipeline to version the releases correctly, for example.

Additionally, I see that this pipeline's sole job builds whatever code is on master and then overwrites the target Docker image on the default 'latest' tag. I'm concerned that there's nothing that validates spiff via its test suites before building the binary and pushing the image.

Finally, since spiff is under only irregular development nowadays, I doubt that in any case we would commit the resources to run and maintain a CI pipeline for it, in which case this pipeline configuration is likely just to degrade over time. Perhaps it would be better suited for inclusion in a collection of concourse examples, or in [your concourse tutorial](https://github.com/drnic/concourse-tutorial)? 

Thanks,
Eric, for the CF Runtime Diego team

**Comment by drnic** [comment]
I've evolved my thinking as I learn more about using concourse - I think pipeline projects need to create their own task docker images; rather than "use a spiff image"




I'm happy for you to close this PR (sent from iPhone)

**Comment by drnic** [comment]
That is - download the spiff.zip like you are doing in your own pipelines.

**Comment by drnic** [comment]
Thanks for your reply! Sorry I hadn't closed the issue already.

**Comment by ematpl** [comment]
Sure thing, I'll close it out. Thanks again for the contribution (and the concourse tutorial--looks nice)! 

Best,
Eric

**Comment by drnic** [comment]
Thanks mate!

**Pull request closed without merging**
